### model
model_name_or_path: /hpc_stor03/sjtu_home/xiran.wang/models/Qwen3-8B
trust_remote_code: true
quantization_bit: 4
quantization_method: bitsandbytes

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: all

### dataset
dataset_dir: data/llamafactory
dataset: kg_cot_standard_635
template: qwen3
cutoff_len: 16384
max_samples: 100000
overwrite_cache: true
preprocessing_num_workers: 8
dataloader_num_workers: 2
val_size: 0.10

### output
output_dir: models/adapters/qwen3-8b-cot-standard
logging_steps: 5
save_strategy: steps
save_steps: 10
save_total_limit: 30
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none
load_best_model_at_end: true
metric_for_best_model: eval_loss
greater_is_better: false

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.03
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 10
