### model
model_name_or_path: /aistor/sjtu/hpc_stor01/home/wangxiran/models/Qwen3-8B
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: all

### dataset
dataset_dir: data/llamafactory
dataset: pro_cot_001_858_complete_schema0413
template: qwen3
cutoff_len: 16384
max_samples: 10
overwrite_cache: true
preprocessing_num_workers: 2
dataloader_num_workers: 0
val_size: 0.20

### output
output_dir: models/adapters/qwen3-8b-cot-pro858-smoke
logging_steps: 1
save_strategy: "no"
plot_loss: false
overwrite_output_dir: true
report_to: none

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 2
learning_rate: 1.0e-4
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.03
bf16: true
ddp_timeout: 180000000
flash_attn: auto
gradient_checkpointing: true

### eval
per_device_eval_batch_size: 1
eval_strategy: "no"
